### ISSUE TITLE
パッケージ管理をpipenvからPoetryに変更

### ISSUE THREAD

**Issue by yrarchi** [yrarchi/household_accounts#28]
pipenvでのPipfile.lockの作成が時間がかかりすぎる（終わらない）ことが頻発するため、これを機にパッケージ管理をPoetryに変更する。

**Comment by yrarchi** [comment]
### Poetry のインストール

はじめ https://python-poetry.org/docs/  を見てインストール実行したが、`This installer is deprecated` と出た
    
    ```bash
    $curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
    Retrieving Poetry metadata
    
    This installer is deprecated. Poetry versions installed using this script will not be able to use 'self update' command to upgrade to 1.2.0a1 or later.
    # Welcome to Poetry!
    
    This will download and install the latest version of Poetry,
    a dependency and package manager for Python.
    
    It will add the `poetry` command to Poetry's bin directory, located at:
    
    $HOME/.poetry/bin
    
    This path will then be added to your `PATH` environment variable by
    modifying the profile files located at:
    
    $HOME/.profile
    $HOME/.bash_profile
    
    You can uninstall at any time by executing this script with the --uninstall option,
    and these changes will be reverted.
    
    Installing version: 1.1.13
      - Downloading poetry-1.1.13-darwin.tar.gz (70.76MB)
    
    Poetry (1.1.13) is installed now. Great!
    
    To get started you need Poetry's bin directory ($HOME/.poetry/bin) in your `PATH`
    environment variable. Next time you log in this will be done
    automatically.
    
    To configure your current shell run `source $HOME/.poetry/env`
    ```


https://python-poetry.org/docs/master/#installing-with-the-official-installer を見て、もう一度インストール

```bash
$curl -sSL https://install.python-poetry.org | python3 -
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/Users/username/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.1.13): Done

Poetry (1.1.13) is installed now. Great!

To get started you need Poetry's bin directory (/Users/username/.local/bin) in your `PATH`
environment variable.

Add `export PATH="/Users/username/.local/bin:$PATH"` to your shell configuration file.

Alternatively, you can call Poetry explicitly with `/Users/username/.local/bin/poetry`.

You can test that everything is set up by executing:

`poetry --version`
```

環境変数の設定
https://python-poetry.org/docs/master/configuration#virtualenvsin-project
    
    ```bash
    $poetry config virtualenvs.in-project true
    ```

**Comment by yrarchi** [comment]
### Poetry でパッケージのインストール

- https://python-poetry.org/docs/basic-usage/#initialising-a-pre-existing-project を参照
- poetry init で質問に順に答えていくとpyproject.tomlが作られる
    
    ```bash
    $poetry init
    
    This command will guide you through creating your pyproject.toml config.
    
    Package name [household_accounts]:
    Version [0.1.0]:
    Description []:
    Author [yrarchi <37015480+yrarchi@users.noreply.github.com>, n to skip]:  n
    License []:
    Compatible Python versions [^3.7]:
    
    Would you like to define your main dependencies interactively? (yes/no) [yes]
    You can specify a package in the following forms:
      - A single name (requests)
      - A name and a constraint (requests@^2.23.0)
      - A git url (git+https://github.com/python-poetry/poetry.git)
      - A git url with a revision (git+https://github.com/python-poetry/poetry.git#develop)
      - A file path (../my-package/my-package.whl)
      - A directory (../my-package/)
      - A url (https://example.com/packages/my-package-0.1.0.tar.gz)
    
    Search for package to add (or leave blank to continue):
    
    Would you like to define your development dependencies interactively? (yes/no) [yes]
    Search for package to add (or leave blank to continue):
    
    Generated file
    
    [tool.poetry]
    name = "household_accounts"
    version = "0.1.0"
    description = ""
    authors = ["Your Name <you@example.com>"]
    
    [tool.poetry.dependencies]
    python = "^3.7"
    
    [tool.poetry.dev-dependencies]
    
    [build-system]
    requires = ["poetry-core>=1.0.0"]
    build-backend = "poetry.core.masonry.api"
    
    Do you confirm generation? (yes/no) [yes]
    ```
```
$poetry install
Creating virtualenv household-accounts in /Users/username/src/household_accounts/.venv
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

Installing the current project: household_accounts (0.1.0)
```

もう古くなっているパッケージが多いが、いったんpipenvと同じバージョンでインストールしていく
```
$poetry add pyocr==0.8

Updating dependencies
Resolving dependencies... (1.6s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing pyocr (0.8)
```

**Comment by yrarchi** [comment]
### 問題なく動くか確認する

バージョン揃えたはずだけど、tesseract でエラーが出る…
    
```bash
    $poetry run python household_accounts
    処理中...
    Traceback (most recent call last):
      File "/Users/username/.pyenv/versions/3.7.8/lib/python3.7/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/Users/username/.pyenv/versions/3.7.8/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "household_accounts/__main__.py", line 7, in <module>
        ocr_results = ocr.main()
      File "household_accounts/ocr.py", line 214, in main
        ocr = OcrReceipt(input_file)
      File "household_accounts/ocr.py", line 28, in __init__
        content_en, content = self.ocr(input_file)
      File "household_accounts/ocr.py", line 44, in ocr
        builder=pyocr.builders.LineBoxBuilder(tesseract_layout=4)
      File "/Users/username/src/household_accounts/.venv/lib/python3.7/site-packages/pyocr/tesseract.py", line 369, in image_to_string
        raise TesseractError(status, errors)
    pyocr.error.TesseractError: (1, b'Error opening data file /usr/local/share/tessdata/jpn.traineddata\nPlease make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.\nFailed loading language \'jpn\'\nTesseract couldn\'t load any languages!\nCould not initialize tesseract.\n')
```

`Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.` と言われているので、環境変数として設定

```bash
export TESSDATA_PREFIX="/Users/username/src/household_accounts"
```

再度実行してみる
```bash
$poetry run python household_accounts
処理中...
Traceback (most recent call last):
  File "/Users/username/.pyenv/versions/3.7.8/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/username/.pyenv/versions/3.7.8/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "household_accounts/__main__.py", line 7, in <module>
    ocr_results = ocr.main()
  File "household_accounts/ocr.py", line 214, in main
    ocr = OcrReceipt(input_file)
  File "household_accounts/ocr.py", line 28, in __init__
    content_en, content = self.ocr(input_file)
  File "household_accounts/ocr.py", line 44, in ocr
    builder=pyocr.builders.LineBoxBuilder(tesseract_layout=4)
  File "/Users/username/src/household_accounts/.venv/lib/python3.7/site-packages/pyocr/tesseract.py", line 387, in image_to_string
    -1, "Unable to find output file (tested {})".format(tested_files)
pyocr.error.TesseractError: (-1, "Unable to find output file (tested ['/var/folders/78/11q2hf1s7ks35kzs9v9ddxg00000gn/T/tmpc67i1jdj/output.html', '/var/folders/78/11q2hf1s7ks35kzs9v9ddxg00000gn/T/tmpc67i1jdj/output.hocr'])")
```

- エラー要因をさぐるため、簡単なコードを試してみる
↓ は動くが、household_accountのコードに合わせた`builder=pyocr.builders.LineBoxBuilder(tesseract_layout=4)`はエラーが出る
    
```bash
import pyocr
from PIL import Image

tool = pyocr.get_available_tools()[0]
print("Will use tool '%s'" % (tool.get_name()))

img1 = Image.open("img/unprocessed/IMG_7479.jpg")
txt1 = tool.image_to_string(
    img1, 
    lang="jpn", 
    builder=pyocr.builders.TextBuilder(tesseract_layout=3)
)
print(txt1)
```
    
- また、以下のことも合わせて考えると、
    - エラー文で`Unable to find output file`としている  https://gitlab.gnome.org/World/OpenPaperwork/pyocr/-/blob/master/src/pyocr/tesseract.py#L376-391
    - class TextBuilder の file_ext は ["txt"] だけど、class LineBoxBuilder の file_ext は ["html", "hocr"]  https://gitlab.gnome.org/World/OpenPaperwork/pyocr/-/blob/master/src/pyocr/builders.py
    
以上より、outputのfileがhocrやhtmlなのが発端となり問題が起きていそう

**Comment by yrarchi** [comment]
### tesseractのエラーへの対応

https://github.com/yrarchi/household_accounts/issues/28#issuecomment-1114224354 で試して、エラーの出なかった file_ext がtxt なのはTextBuilder のみ
元々使用していた LineBoxBuilder は行単位でOCRして文字位置も合わせて返すが、文字位置はその後使用していない。TextBuilder で返ってくるOCR結果の文字列は改行文字を含むことを確認したので、改行文字でsplitするようにすれば、今回の用途を満たす。
TextBuilderに切り替えることにする。

**Comment by yrarchi** [comment]
Poetryに変更し、元のように動くことを確認したのでこのissueは閉じる
